export const COPY = {
  productName: '智能收藏',
  actionTitle: '智能收藏当前网页',
  productDescription: '将当前网页收藏到最合适的现有目录',
  loading: '正在读取当前网页…',
  classifying: '正在判断最合适的收藏目录…',
  consentTitle: '先确认 JEV 数据共享',
  consentIntro: '智能分类可能会将以下信息发送给 JEV：',
  consentItems: [
    '当前网页的标题、网址、域名、描述、H1 和最多 4,000 个可见字符',
    '可分类目录的完整路径',
    '若有目录示例，会发送少量示例的标题和域名，用于说明目录含义',
  ],
  consentAccept: '同意并继续',
  consentDecline: '不共享，手动选择',
  candidatesTitle: '选择一个候选目录',
  allFoldersTitle: '全部可分类目录',
  chooseFolder: '选择目录',
  saveHere: '收藏到此处',
  savedTitle: '已收藏',
  automaticSavedTitle: '已自动收藏',
  savedPathPrefix: '保存位置：',
  duplicateTitle: '发现重复收藏',
  duplicateIntro: '此网页已存在于以下位置。默认不会更改或新增任何收藏：',
  preserveExisting: '保留现有收藏',
  createAnotherCopy: '仍然创建一个副本',
  reclassifyExisting: '重新分类并移动此收藏',
  duplicatePreservedTitle: '已保留现有收藏',
  duplicatePreservedBody: '未创建、移动或删除任何收藏。',
  moveExistingHere: '将现有收藏移动到此处',
  changeDestination: '更改位置',
  undo: '撤销',
  undoneTitle: '已撤销',
  undoneBody: '已恢复到本次智能收藏开始前的状态。',
  settings: '设置',
  openSettings: '打开设置',
  pendingSavedTitle: '已保存到待分类目录',
  retryClassification: '重试智能分类',
  classificationUnavailable: '智能分类暂时不可用。收藏已保留，请稍后重试。',
  invalidApiKey: 'JEV API 密钥无效。收藏已保留，请先修复密钥。',
  invalidClassificationRequest: 'JEV 无法处理本次请求。收藏已保留，请手动选择目录。',
  malformedClassificationResponse: 'JEV 返回了无法识别的结果。收藏已保留，请重试。',
  noEligibleFolders: '没有可分类目录。收藏已保留，请先在 Chrome 中创建收藏目录。',
  noMatchingFolder: '没有合适的可分类目录。收藏已保留，请手动选择目录。',
  pageChangedBeforeCapture: '网页在读取完成前发生了变化。本次未收藏，请重试。',
  incognitoDisabled: '无痕窗口中已停用智能收藏，未发送或写入任何数据。',
  folderSelectionUnavailable: '目录设置已更新，请从当前可分类目录中重新选择。',
  bookmarkChangedExternally: '收藏已被外部删除或更改。为避免误操作，本次更改或撤销已停止。',
  unsupportedPage: '此页面不会发送给 JEV，请手动选择目录。',
  genericError: '操作未完成，请重试。',
  signalTitle: '查看本次使用的网页信号',
  signalUrl: '网址',
  signalDomain: '域名',
  signalDescription: '页面描述',
  signalHeading: '主标题',
  signalText: '可见文本',
  settingsTitle: 'JEV 设置',
  keyLabel: 'JEV API 密钥',
  keyPlaceholder: '输入新密钥',
  keyStored: '已保存：',
  keyMissing: '尚未保存密钥',
  unencryptedWarning: '密钥保存在本机扩展存储中，不会加密。请仅在信任的设备上使用。',
  saveKey: '保存 / 替换',
  testKey: '测试连接',
  clearKey: '清除密钥',
  keySaved: '密钥已保存',
  keyCleared: '密钥已清除',
  keyValid: '连接成功',
  keyInvalid: '连接失败，请检查密钥',
  consentRequiredForTest: '请先允许 JEV 数据共享，再测试连接',
  emptyKey: '请先输入密钥',
  consentSetting: 'JEV 数据共享',
  consentGranted: '已同意',
  consentDeclined: '已关闭',
  consentUnknown: '尚未选择',
  allowConsent: '允许',
  declineConsent: '关闭',
  folderExclusionsTitle: '可分类目录',
  folderExclusionsIntro: '取消勾选可排除整个目录子树。被父目录排除的子目录仍会显示，但不能单独恢复。',
  folderDescendantCount: (count: number) => `影响 ${count} 个子目录`,
  folderTreeEmpty: 'Chrome 中还没有可管理的收藏目录。',
} as const;
