export const COPY = {
  productName: '智能收藏',
  actionTitle: '智能收藏当前网页',
  productDescription: '将当前网页收藏到最合适的现有目录',
  loading: '正在读取当前网页…',
  classifying: '正在判断最合适的收藏目录…',
  consentTitle: '先确认 JEV 数据共享',
  consentIntro: '智能分类可能会将以下信息发送给 JEV：',
  consentItems: [
    '当前网页的标题、网址、域名、描述、H1 和最多 4,000 个可见字符',
    '可分类目录的完整路径',
    '若有目录示例，会发送少量示例的标题和域名，用于说明目录含义',
  ],
  consentAccept: '同意并继续',
  consentDecline: '不共享，手动选择',
  candidatesTitle: '选择一个候选目录',
  allFoldersTitle: '全部可分类目录',
  chooseFolder: '选择目录',
  saveHere: '收藏到此处',
  savedTitle: '已收藏',
  savedPathPrefix: '保存位置：',
  settings: '设置',
  openSettings: '打开设置',
  classificationUnavailable: '智能分类暂时不可用，仍可手动选择目录。',
  noEligibleFolders: '没有可分类目录。请先在 Chrome 中创建收藏目录。',
  unsupportedPage: '此页面不会发送给 JEV，请手动选择目录。',
  genericError: '操作未完成，请重试。',
  signalTitle: '查看本次使用的网页信号',
  signalUrl: '网址',
  signalDomain: '域名',
  signalDescription: '页面描述',
  signalHeading: '主标题',
  signalText: '可见文本',
  settingsTitle: 'JEV 设置',
  keyLabel: 'JEV API 密钥',
  keyPlaceholder: '输入新密钥',
  keyStored: '已保存：',
  keyMissing: '尚未保存密钥',
  unencryptedWarning: '密钥保存在本机扩展存储中，不会加密。请仅在信任的设备上使用。',
  saveKey: '保存 / 替换',
  testKey: '测试连接',
  clearKey: '清除密钥',
  keySaved: '密钥已保存',
  keyCleared: '密钥已清除',
  keyValid: '连接成功',
  keyInvalid: '连接失败，请检查密钥',
  consentRequiredForTest: '请先允许 JEV 数据共享，再测试连接',
  emptyKey: '请先输入密钥',
  consentSetting: 'JEV 数据共享',
  consentGranted: '已同意',
  consentDeclined: '已关闭',
  consentUnknown: '尚未选择',
  allowConsent: '允许',
  declineConsent: '关闭',
} as const;
